apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: app-cluster
  region: us-east-1
iam:
  withOIDC: true
vpc:
  id: "vpc-00d782f4a042f94bb"
  subnets:
    private:
      us-east-1a: { id: "subnet-034fcf9f7c470dca5" }
      us-east-1b: { id: "subnet-0beb08897f9a19b9f" }
    public:
      us-east-1a: { id: "subnet-02dec9551748031b0" }
      us-east-1b: { id: "subnet-0adc45a7832fc7496" }
nodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
