apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
  labels:
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: denisdugar/cicd-test:{{ .newTag }}
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: regcred
