apiVersion: v1
kind: Secret
metadata:
  name: image-updater-git-cred
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/denisdugar/ci-cd-tutorial-sample-app.git
  username: denisdugar
  password: <github_token>

