pipeline {
    agent any
    environment {
        registry           = "denisdugar/cicd-test"
        registryCredential = 'dockerhub_id'
    }
    stages {
        stage('Clone') {
            steps { git 'https://github.com/denisdugar/ci-cd-tutorial-sample-app.git' }
        }
        stage('Build') {
            steps {
                script {
                    env.IMAGE_TAG = sh(
                        script: "head /dev/urandom | tr -dc 'a-z0-9' | head -c8",
                        returnStdout: true
                    ).trim()
                    dockerImage = docker.build("${registry}:${env.IMAGE_TAG}")
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Cleanup') {
            steps {
                sh "docker rmi ${registry}:${env.IMAGE_TAG}"
            }
        }
    }
}
